on: 
  workflow_dispatch:
    inputs:
      mode:
        description: 'Enter Application Mode'
        required: true
        default: 'full'

jobs:
  Build_API:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.mode == 'full' || github.event.inputs.mode == 'minmum' }}
    steps:
      - run: |
          echo "Build API"

  Build_Jupyter:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.mode == 'full' }}
    steps:
      - run: |
          echo "Build Jupyter"

  Build_Frontend:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.mode == 'full' || github.event.inputs.mode == 'minmum' }}
    steps:
      - run: |
          echo " Build Frontend"
  Create_Server:
    runs-on: ubuntu-latest
    needs: [Build_API,Build_Jupyter,Build_Frontend]
    if: needs.Build_API.result == 'success' || needs.Build_API.result == 'skipped' || needs.Build_Jupyter.result == 'success' || needs.Build_Jupyter.result == 'skipped' || needs.Build_Frontend.result == 'success' || needs.Build_Frontend.result == 'skipped'
    steps:
      - run: |
          echo "Creater Server"

