on: 
  workflow_dispatch:
    inputs:
      mode:
        description: 'Enter Application Mode'
        required: true
        default: 'full'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.mode }} == 'full'
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.mode }}!"
